import { IslandContent } from "types.slint";

export struct MediaState {
    app-name: string,
    app-icon: image,

    title: string,
    artist: string,
    album: string,

    album-art: image,

    playing: bool,

    duration-ms: int,
}

export struct NotificationState {
    id: string,

    app-name: string,
    app-icon: image,
    
    title: string,
    body: string,
}

export global IslandData {
    in-out property <bool> expanded;
    in-out property <bool> collapsed;

    in property <bool> mic;
    in property <bool> camera;

    in property <IslandContent> content;

    in property <MediaState> media;
    in property <NotificationState> notification;

    in property <[float]> spectrum;
    in property <int> media-position;

    callback action(name: string, payload: string);
}

export global Config {
    in property <float> scale: 1.0;
    in property <length> y-offset: 8px;
    in property <bool> shadows: true;
    in property <bool> completely-hidden: false;

    in property <int> notification-timeout-ms: 3000;
}

export global Assets {
    out property <image> fallback-app: @image-url("../../assets/images/fallback-app.png");
    out property <image> fallback-media: @image-url("../../assets/images/fallback-media.png");

    out property <image> play-img: @image-url("../../assets/images/play.png");
    out property <image> pause-img: @image-url("../../assets/images/pause.png");
    out property <image> prev-img: @image-url("../../assets/images/prev.png");
    out property <image> next-img: @image-url("../../assets/images/next.png");
}