import { IslandData, Assets } from "../global.slint";
import { Metrics } from "../theme/Metrics.slint";

export component MediaControls inherits HorizontalLayout {
    spacing: Metrics.spacing-lg;
    alignment: center;

    property <length> size: Metrics.icon-xl;
    
    prev := Rectangle {
        width: size; 
        height: size; 

        Image {
            width: parent.width;
            height: parent.height;
            source: Assets.prev-img;
        }

        TouchArea {
            width: parent.width;
            height: parent.height;
            mouse-cursor: pointer;

            clicked => {
                IslandData.action("previous", "");
            }
        }
    }
    play-pause := Rectangle {
        width: size; 
        height: size; 

        Image {
            width: parent.width;
            height: parent.height;
            source: IslandData.media.playing ? Assets.pause-img : Assets.play-img;
        }

        TouchArea {
            width: parent.width;
            height: parent.height;
            mouse-cursor: pointer;
            
            clicked => {
                IslandData.action("toggle-playback", "");
            }
        }
    }

    next := Rectangle {
        width: size; 
        height: size; 

        Image {
            width: parent.width;
            height: parent.height;
            source: Assets.next-img;
        }
        
        TouchArea {
            width: parent.width;
            height: parent.height;
            mouse-cursor: pointer;
            
            clicked => {
                IslandData.action("next", "");
            }
        }
    }
}