import { IslandData } from "../global.slint";
import { Metrics } from "../theme/Metrics.slint";

export component SpectrumBars inherits HorizontalLayout {
    horizontal-stretch: 0;
    spacing: Metrics.spacing-xs;

    for band[i] in IslandData.spectrum: Rectangle {
        private property <length> size: max(
            Metrics.spectrum-bar-min-height, 
            band * Metrics.spectrum-bar-height
        );

        width: Metrics.spectrum-bar-width;
        height: size;

        y: (parent.height - self.height) / 2;

        border-radius: self.width / 2;

        background: hsv(
            80 + (i * 120 / 27),
            45%,
            88%
        );
    }
}