import { IslandData } from "../global.slint";
import { Metrics } from "../theme/Metrics.slint";

export component Timeline inherits Rectangle {
    height: Metrics.timeline-hitbox;

    property <float> progress: IslandData.media.duration-ms > 0 
                                ? IslandData.media-position * 1.0 / IslandData.media.duration-ms * 1.0
                                : 0;

    property <float> local-progress: ta.has-hover 
                                        ? ta.mouse-x * 1.0 / self.width
                                        : progress;

    pure function pad-zero(n: int) -> string {
        return n < 10 ? "0\{n}" : "\{n}";
    }

    pure function format-ms(ms: int) -> string {
        let total-s: int = ms / 1000;
        let s: int = Math.mod(total-s, 60);
        let total-m: int = total-s / 60;
        let m: int = Math.mod(total-m, 60);
        let h: int = total-m / 60;

        if (h > 0) {
            return "\{h}:\{pad-zero(m)}:\{pad-zero(s)}";
        } else {
            return "\{m}:\{pad-zero(s)}";
        }
    }

    Rectangle {
        x: clamp((parent.width * local-progress) - (self.width / 2), 0px, parent.width - self.width);
        y: -(self.height) - Metrics.timeline-label-offset;
        z: 2;
        visible: ta.has-hover ? true : false;

        background: #fff;
        border-width: Metrics.border-width;
        border-radius: self.height / 2;
        horizontal-stretch: 0;

        width: layout.preferred-width;
        height: layout.preferred-height;

        layout := HorizontalLayout {
            padding-top: Metrics.inset-xs;
            padding-bottom: Metrics.inset-xs;
            padding-left: Metrics.inset-md;
            padding-right: Metrics.inset-md;
            alignment: center;
            y: (parent.height - self.height) / 2;

            Text {
                text: format-ms(IslandData.media.duration-ms * local-progress);
                font-size: Metrics.fs-100;
                color: #000;
                letter-spacing: Metrics.letter-spacing;
                vertical-alignment: center;
                horizontal-alignment: center;
                font-weight: 550;
            }
        }
    }

    Rectangle {
        height: Metrics.inset-xs;
        width: parent.width;
        border-radius: self.height / 2;
        background: #ffffff65;
        x: 0;
        y: (parent.height - self.height) / 2;

        Rectangle {
            opacity: ta.has-hover ? 1 : 0;
    
            height: parent.height;
            width: parent.width * local-progress;
            border-radius: parent.border-radius;
            background: #ffffff9c;
            x: 0;
            y: (parent.height - self.height) / 2;
            
            animate opacity {
                duration: 250ms;
                easing: ease-in;
            }
        }
        
        Rectangle {
            height: parent.height;
            width: parent.width * (ta.pressed ? local-progress : progress);
            border-radius: parent.border-radius;
            background: #fff;
            x: 0;
            
            Rectangle {
                private property <length> size: Metrics.icon-xs;

                opacity: ta.has-hover ? 1 : 0;
    
                height: size;
                width: size;
                border-radius: self.height / 2;
                background: #fff;
    
                x: parent.width - (self.width / 2);
    
                animate opacity {
                    duration: 250ms;
                    easing: ease-in;
                }
            }
        }
    }

    ta := TouchArea {
        width: parent.width;
        height: parent.height;
        mouse-cursor: pointer;

        pointer-event(ev) => {
            if (ev.button == PointerEventButton.left && ev.kind == PointerEventKind.up) {
                IslandData.action("seek", "\{Math.round(local-progress * IslandData.media.duration-ms)}");
            }
        }
    }
}